### PR TITLE
fix and update result page (resolves #317)

### LINKED ISSUE #317: Results-Page
We need to rework the results page (it is called Reports at the moment and just dumps the json files).

Dependency: #21 

Table-like view with three layers: measurement-type (ping, http-download, ...), task, and result. The following picture shows what we have in mind:

glimpse_gui

The task-line could show one or two aggregations over all results, the result line should show the interesting values for each result.

Most things should be hidden at first, for example only five tasks per measurement-type. You can get more tasks by clicking "...". If you click on a task you get the five latest results, by clicking "..." you get the next five and so on.

### PR DESCRIPTION
**Pull request by monstermunchkin**

### CODE REVIEW

File: src/libclient/result/resultmodel.cpp [hunk 1]
```diff
@@ -23,6 +23,24 @@ class ResultModel::Private : public QObject
         scheduler = Client::instance()->scheduler();
     }
 
+    void sort(ExtResultList &list)
+    {
+        for (int n = 0; n <list.count(); n++)
```
Comment (MKV21) [inline src/libclient/result/resultmodel.cpp]: Honor coding guidelines.
